name = "Narxoz Create"
author = "Yaggi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bbd0fc5a5b56598e909056fc8fc1eaf6e5140ab03485e0926bbcc1ae0f8e691"

[versions]
minecraft = "1.21.1"
