name = "Narxoz Create"
author = "Yaggi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cedafa60aaca59bce2246d7df6104cddcb05cb1ec23dc9b495f82d7496db123"

[versions]
minecraft = "1.21.1"
