name = "Narxoz Create"
author = "Yaggi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeade91875c8111299a6b03903de1735449663a736a320558bfdd0f84340d836"

[versions]
minecraft = "1.21.1"
